name = input("what is your name: ")
print("Hello Comrade",name)
lastname = input("what is your last name: ")
print("cool,")
season = input("what is your favorate season: ")
print("wow comrade" ,name ,lastname""is my favorate to.")
